            - name: crowdin-action
  # You may pin to the exact commit or the version.
  # uses: crowdin/github-action@6ed209d411599a981ccb978df3be9dc9b8a81699
  uses: crowdin/github-action@v2.1.1
  with:
    # Upload sources to Crowdin
    upload_sources: # optional, default is true
    # Additional arguments which will be passed to the `upload sources` cli command
    upload_sources_args: # optional, default is 
    # Upload translations to Crowdin
    upload_translations: # optional, default is false
    # Use this option to upload translations for a single specified language - Case-Sensitive
    upload_language: # optional
    # Automatically approves uploaded translations
    auto_approve_imported: # optional, default is false
    # Defines whether to add translation if it is equal to source string in Crowdin project
    import_eq_suggestions: # optional, default is false
    # Additional arguments which will be passed to the `upload translations` cli command
    upload_translations_args: # optional, default is 
    # Defines whether to download source files from the Crowdin project
    download_sources: # optional, default is false
    # Push downloaded sources to the branch
    push_sources: # optional, default is true
    # Additional arguments which will be passed to the `download sources` cli command
    download_sources_args: # optional, default is 
    # Defines whether to download translation files from the Crowdin project
    download_translations: # optional, default is false
    # Use this option to download translations for a single specified language
    download_language: # optional
    # Download bundle from Crowdin project (by ID)
    download_bundle: # optional, default is 
    # Skip untranslated strings in exported files (does not work with .docx, .html, .md and other document files)
    skip_untranslated_strings: # optional, default is false
    # Omit downloading not fully translated files
    skip_untranslated_files: # optional, default is false
    # Include approved translations only in exported files. If not combined with --skip-untranslated-strings option, strings without approval are fulfilled with the source language
    export_only_approved: # optional, default is false
    # Push downloaded translations to the branch
    push_translations: # optional, default is true
    # Commit message for download translations
    commit_message: # optional, default is New Crowdin translations by GitHub Action
    # To download translations to the specified version branch
    localization_branch_name: # optional, default is l10n_crowdin_action
    # Create pull request after pushing to branch
    create_pull_request: # optional, default is true
    # The title of the new pull request
    pull_request_title: # optional, default is New Crowdin translations by GitHub Action
    # The contents of the pull request
    pull_request_body: # optional
    # Add up to 10 assignees to the created pull request (separated by comma)
    pull_request_assignees: # optional
    # Usernames of people from whom a review is requested for this pull request (separated by comma)
    pull_request_reviewers: # optional
    # Team slugs from which a review is requested for this pull request (separated by comma)
    pull_request_team_reviewers: # optional
    # To add labels for created pull request
    pull_request_labels: # optional
    # Create pull request to specified branch instead of default one
    pull_request_base_branch_name: # optional
    # Additional arguments which will be passed to the `download translations` cli command
    download_translations_args: # optional, default is 
    # Skip default git checkout on GITHUB_REF
    skip_ref_checkout: # optional, default is false
    # Option to upload or download files to the specified version branch in your Crowdin project
    crowdin_branch_name: # optional
    # Option to specify a path to the configuration file, without / at the beginning
    config: # optional
    # Option to preview the list of managed files
    dryrun_action: # optional, default is false
    # Option to configure the base URL of GitHub server, if using GHE.
    github_base_url: # optional, default is github.com
    # Options to configure the base URL of GitHub server for API requests, if using GHE and different from api.github_base_url.
    github_api_base_url: # optional
    # Option to configure GitHub user name on commits.
    github_user_name: # optional, default is Crowdin Bot
    # Option to configure GitHub user email on commits.
    github_user_email: # optional, default is support+bot@crowdin.com
    # GPG private key in ASCII-armored format
    gpg_private_key: # optional
    # GPG Passphrase
    gpg_passphrase: # optional, default is 
    # Numerical ID of the project
    project_id: # optional
    # Personal access token required for authentication
    token: # optional
    # Base URL of Crowdin server for API requests execution
    base_url: # optional
    # Path to your project directory on a local machine, without / at the beginning
    base_path: # optional
    # Path to the source files, without / at the beginning
    source: # optional
    # Path to the translation files
    translation: # optional
    # Crowdin CLI command to execute
    command: # optional
    # Additional arguments which will be passed to the Crowdin CLI command
    command_args: # optional
          
